//
//  SubContainerMacro.swift
//  InnoDIMacros
//
//  First-class nested containers. Public `@SubContainer` validates usage;
//  the sibling-complete `@DIContainer` member-attribute phase attaches the
//  hidden support owner that expands into two roles:
//
//  1. **Peer storage** — per-member private declarations that hold the cached
//     child instance (`.shared` scope) and/or the test override wedges that
//     the parent `Overrides` builder writes into during init.
//  2. **Accessor** — a getter that either returns the cached child (for
//     `.shared`) or delegates to a parent-synthesized helper that builds a
//     fresh child on every read (for `.transient`).
//
//  The init-time wiring (assigning `_storage_sub_<name>`, applying
//  `_override_sub_<name>`, emitting the helper function for `.transient`) is
//  generated by `DIContainerMacro` / `DIContainerCodeGenerator`, which sees
//  every `@SubContainer` member via `DIContainerExpansionModel.subContainerMembers`.
//  This ownership lets container-wide validation suppress peers and accessors
//  together even though attached member macro inputs do not retain siblings.
//

import InnoDICore
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

public struct SubContainerMacro {}
public struct InnoDISubContainerAccessorMacro {}

extension SubContainerMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        let variable = declaration.as(VariableDeclSyntax.self)
        let memberName = variable?
            .bindings.first?.pattern.as(IdentifierPatternSyntax.self)?.identifier
        let subContainerAttributes = variable.map {
            findInnoDIAttributes(named: "SubContainer", in: $0.attributes)
        } ?? []
        if subContainerAttributes.count > 1 {
            if let diagnosticOwner = subContainerAttributes.dropFirst().first,
               hasSameSubContainerSourceLocation(node, diagnosticOwner, in: context) {
                context.emit(
                    SimpleDiagnostic.subDuplicateAttribute(
                        memberName: memberName?.text ?? "<unknown>"
                    ),
                    at: Syntax(diagnosticOwner)
                )
            }
            return []
        }
        let membership = directDIContainerMembership(declaration, in: context)
        if membership == .unsupported {
            // The conditional declaration or unsupported parent container
            // owns the terminal diagnostic. Do not add an escaped-name error
            // for source that cannot enter the child model at all.
            return []
        }

        if let memberName, isEscapedInnoDIIdentifier(memberName) {
            context.emit(
                SimpleDiagnostic.subEscapedPropertyIdentifier(
                    memberName: unescapedInnoDIIdentifierName(memberName)
                ),
                at: Syntax(memberName)
            )
            return []
        }

        if membership == .none {
            context.emit(
                SimpleDiagnostic.subRequiresDirectContainerMember(
                    memberName: memberName?.text ?? "<unknown>"
                ),
                at: Syntax(node)
            )
        }

        // The sibling-complete @DIContainer member-attribute role attaches
        // `_InnoDISubContainerAccessor`, which exclusively owns every storage
        // and accessor declaration. Public @SubContainer only validates use.
        return []
    }
}

private func hasSameSubContainerSourceLocation(
    _ lhs: AttributeSyntax,
    _ rhs: AttributeSyntax,
    in context: some MacroExpansionContext
) -> Bool {
    guard let lhsLocation = context.location(of: lhs),
          let rhsLocation = context.location(of: rhs) else {
        return Syntax(lhs).id == Syntax(rhs).id
    }

    return lhsLocation.file.trimmedDescription == rhsLocation.file.trimmedDescription
        && lhsLocation.line.trimmedDescription == rhsLocation.line.trimmedDescription
        && lhsLocation.column.trimmedDescription == rhsLocation.column.trimmedDescription
}

extension InnoDISubContainerAccessorMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard parseSubContainerAccessorRecovery(node) == false,
              let variable = declaration.as(VariableDeclSyntax.self),
              let identifier = variable.bindings.first?
                .pattern.as(IdentifierPatternSyntax.self)?.identifier,
              !isReservedGeneratedSubContainerMemberName(identifier),
              directDIContainerMembership(declaration, in: context) == .supported,
              !directDIContainerHasReservedGeneratedName(declaration, in: context) else {
            return []
        }
        guard let subContainerAttribute = findInnoDIAttribute(
            named: "SubContainer",
            in: variable.attributes
        ) else { return [] }

        return makeSubContainerPeers(
            from: subContainerAttribute,
            declaration: declaration,
            in: context
        )
    }
}

extension InnoDISubContainerAccessorMacro: AccessorMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingAccessorsOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
        guard let variable = declaration.as(VariableDeclSyntax.self),
              let identifier = variable.bindings.first?
                .pattern.as(IdentifierPatternSyntax.self)?.identifier else {
            return [failedDIValidationRecoveryAccessor(message: "Invalid generated @SubContainer accessor owner")]
        }

        if isEscapedInnoDIIdentifier(identifier) {
            // Public @SubContainer owns this diagnostic and recovery accessor.
            return []
        }
        if isReservedGeneratedSubContainerMemberName(identifier) {
            return [failedDIValidationRecoveryAccessor(message: "Invalid reserved @SubContainer name")]
        }

        guard let subContainerAttribute = findInnoDIAttribute(
            named: "SubContainer",
            in: variable.attributes
        ) else {
            if !isDirectMemberOfSupportedDIContainer(declaration, in: context) {
                context.emit(
                    SimpleDiagnostic.subGeneratedAccessorManualAttachment(
                        memberName: identifier.text
                    ),
                    at: Syntax(node)
                )
            }
            return [failedDIValidationRecoveryAccessor(message: "Invalid generated @SubContainer accessor owner")]
        }

        guard parseSubContainerAccessorRecovery(node) == false,
              directDIContainerMembership(declaration, in: context) == .supported,
              !directDIContainerHasReservedGeneratedName(declaration, in: context) else {
            return [failedDIValidationRecoveryAccessor(message: "Invalid @SubContainer dependency")]
        }

        return makeSubContainerAccessors(
            from: subContainerAttribute,
            declaration: declaration,
            in: context
        )
    }
}

private func makeSubContainerPeers(
    from attribute: AttributeSyntax,
    declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
) -> [DeclSyntax] {
    guard let info = extractPeerInfo(
        from: attribute,
        declaration: declaration,
        in: context
    ) else {
        return []
    }

    var declarations: [DeclSyntax] = []

    // `.shared` caches the first-built child in a private stored property.
    // `.transient` rebuilds on every accessor read and therefore needs no
    // storage — the override wedges below are still emitted in both scopes so
    // `Overrides.<name>` / `Overrides.<name>Overrides` can thread through init.
    if info.scope == .shared {
        declarations.append(
            storagePeerDecl(
                name: "_storage_sub_\(info.name)",
                type: info.type,
                optional: false
            )
        )
    }

    declarations.append(
        storagePeerDecl(
            name: "_override_sub_\(info.name)",
            type: info.type,
            optional: true
        )
    )
    declarations.append(
        subContainerApplyOverridePeerDecl(
            name: info.name,
            childType: info.type,
            isMainActor: info.isMainActor
        )
    )

    // `.transient` scope needs a lazily-reinvoked builder closure. The parent
    // container initializes this peer after every other storage slot.
    if info.scope == .transient {
        declarations.append(
            subContainerBuildClosurePeerDecl(
                name: info.name,
                childType: info.type,
                isMainActor: info.isMainActor
            )
        )
    }

    return declarations
}

private func makeSubContainerAccessors(
    from attribute: AttributeSyntax,
    declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
) -> [AccessorDeclSyntax] {
    guard let info = extractPeerInfo(
        from: attribute,
        declaration: declaration,
        in: context
    ) else {
        return []
    }

    let bodyExpr: ExprSyntax
    switch info.scope {
    case .shared:
        // Cached child — plain storage read.
        bodyExpr = ExprSyntax(
            DeclReferenceExprSyntax(baseName: .identifier("_storage_sub_\(info.name)"))
        )

    case .transient:
        // Fresh child each read. The stored builder closure
        // `_innoDISubBuild_<name>` is assigned by the parent init after
        // all other storage is initialized. Invoking it here re-reads
        // the captured parent snapshot, which yields a new child
        // instance per call.
        bodyExpr = ExprSyntax(FunctionCallExprSyntax(
            calledExpression: ExprSyntax(
                DeclReferenceExprSyntax(baseName: .identifier("_innoDISubBuild_\(info.name)"))
            ),
            leftParen: .leftParenToken(),
            arguments: LabeledExprListSyntax([]),
            rightParen: .rightParenToken()
        ))
    }

    let getter = AccessorDeclSyntax(
        accessorSpecifier: .keyword(.get),
        body: CodeBlockSyntax(
            statements: CodeBlockItemListSyntax([
                returnStmt(expr: bodyExpr)
            ])
        )
    )
    return [getter]
}

func parseSubContainerAccessorRecovery(_ attribute: AttributeSyntax) -> Bool? {
    guard let arguments = attribute.arguments?.as(LabeledExprListSyntax.self),
          let recoveryArgument = arguments.first(where: { $0.label?.text == "recovery" }) else {
        return nil
    }
    return InnoDICore.parseBoolArgument(recoveryArgument.expression).value
}

private func isReservedGeneratedSubContainerMemberName(
    _ identifier: TokenSyntax
) -> Bool {
    let name = unescapedInnoDIIdentifierName(identifier)
    return name == "InnoDI"
        || reservedGeneratedMemberPrefixes.contains { name.hasPrefix($0) }
}

// MARK: - Shared helpers

private struct SubContainerPeerInfo {
    let name: String
    let type: TypeSyntax
    let scope: SubContainerScopeValue
    let isMainActor: Bool
}

private func extractPeerInfo(
    from attribute: AttributeSyntax,
    declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
) -> SubContainerPeerInfo? {
    guard !isEnclosedByUnsupportedDIContainer(declaration, in: context) else {
        return nil
    }

    guard let varDecl = declaration.as(VariableDeclSyntax.self) else { return nil }
    guard let binding = varDecl.bindings.first,
          let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
          !isEscapedInnoDIIdentifier(identifier.identifier),
          let typeAnnotation = binding.typeAnnotation else {
        return nil
    }

    let args = InnoDICore.parseSubContainerArguments(attribute)
    // When `scope:` is missing we stay silent here: `DIContainerParser` sees
    // the same attribute and routes the error through the container-level
    // validator, which attaches the diagnostic to the attribute node.
    guard InnoDICore.isLocallyValidSubContainerConfiguration(args),
          let scope = args.scope else {
        return nil
    }

    // Prefer lexical expansion context when SwiftSyntaxMacros provides it,
    // then fall back to walking out from the attribute and declaration nodes.
    // If no enclosing @DIContainer is visible through any path we conservatively
    // treat the property as non-MainActor.
    return SubContainerPeerInfo(
        name: identifier.identifier.text,
        type: typeAnnotation.type,
        scope: scope,
        isMainActor: (
            enclosingDIContainerInfo(in: context) ??
            enclosingDIContainerInfo(startingAt: Syntax(attribute)) ??
            enclosingDIContainerInfo(startingAt: Syntax(declaration))
        )?.mainActor == true
    )
}

/// `private let _override_sub_apply_<name>: ([@MainActor] (inout <ChildType>._InnoDIMountOverrides) -> Void)?`
///
/// Optional wedge used by the parent `Overrides.<name>Overrides` slot to
/// forward a trailing-closure override block to the child's own convenience
/// init. Input-only child containers synthesize an empty `Overrides` type, so
/// this closure still type-checks and simply applies no overrideable members
/// until the child grows `.shared`, `.transient`, or nested child slots.
private func subContainerApplyOverridePeerDecl(
    name: String,
    childType: TypeSyntax,
    isMainActor: Bool
) -> DeclSyntax {
    let trimmed = childType.trimmedDescription
    let applyType = overrideApplyClosureType(
        overridesTypeDescription: "\(trimmed).\(innoDIMountOverridesTypeName)",
        isMainActor: isMainActor,
        isOptional: true
    )
    let decl = VariableDeclSyntax(
        modifiers: DeclModifierListSyntax([
            DeclModifierSyntax(name: .keyword(.private, trailingTrivia: .space))
        ]),
        bindingSpecifier: .keyword(.let, trailingTrivia: .space),
        bindings: PatternBindingListSyntax([
            PatternBindingSyntax(
                pattern: IdentifierPatternSyntax(identifier: .identifier("_override_sub_apply_\(name)")),
                typeAnnotation: TypeAnnotationSyntax(
                    colon: .colonToken(trailingTrivia: .space),
                    type: applyType
                )
            )
        ])
    )
    return DeclSyntax(decl)
}

private func enclosingDIContainerInfo(startingAt syntax: Syntax) -> DIContainerAttributeInfo? {
    var current: Syntax? = syntax.parent

    while let node = current {
        if let declGroup = declGroupSyntax(from: node),
           let info = diContainerAttributeInfo(in: declGroup) {
            return info
        }
        current = node.parent
    }

    return nil
}

private func enclosingDIContainerInfo(in context: some MacroExpansionContext) -> DIContainerAttributeInfo? {
    // SwiftSyntax orders lexical context innermost-to-outermost. The nearest
    // container owns isolation when supported containers are nested.
    for node in context.lexicalContext {
        if let declGroup = declGroupSyntax(from: node),
           let info = diContainerAttributeInfo(in: declGroup) {
            return info
        }
    }

    return nil
}

private func diContainerAttributeInfo(in declaration: some DeclGroupSyntax) -> DIContainerAttributeInfo? {
    parseDIContainerAttribute(declaration.attributes)
}

private func declGroupSyntax(from syntax: Syntax) -> (any DeclGroupSyntax)? {
    if let structDecl = syntax.as(StructDeclSyntax.self) {
        return structDecl
    }
    if let classDecl = syntax.as(ClassDeclSyntax.self) {
        return classDecl
    }
    if let actorDecl = syntax.as(ActorDeclSyntax.self) {
        return actorDecl
    }
    if let enumDecl = syntax.as(EnumDeclSyntax.self) {
        return enumDecl
    }
    return nil
}
