//
//  SubContainerMacro.swift
//  InnoDIMacros
//
//  Phase M — first-class nested containers. `@SubContainer` expands into two
//  roles:
//
//  1. **Peer storage** — per-member private declarations that hold the cached
//     child instance (`.shared` scope) and/or the test override wedges that
//     the parent `Overrides` builder writes into during init.
//  2. **Accessor** — a getter that either returns the cached child (for
//     `.shared`) or delegates to a parent-synthesized helper that builds a
//     fresh child on every read (for `.transient`).
//
//  The init-time wiring (assigning `_storage_sub_<name>`, applying
//  `_override_sub_<name>`, emitting the helper function for `.transient`) is
//  generated by `DIContainerMacro` / `DIContainerCodeGenerator`, which sees
//  every `@SubContainer` member via `DIContainerExpansionModel.subContainerMembers`.
//  Keeping the split here avoids duplicating "iterate every parent member"
//  logic inside an accessor macro that has no sibling visibility.
//

import InnoDICore
import SwiftSyntax
import SwiftSyntaxMacros

public struct SubContainerMacro {}

extension SubContainerMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let info = extractPeerInfo(from: node, declaration: declaration) else {
            return []
        }

        var decls: [DeclSyntax] = []

        // `.shared` caches the first-built child in a private stored property.
        // `.transient` rebuilds on every accessor read and therefore needs no
        // storage — the override wedges below are still emitted in both
        // scopes so `Overrides.<name>` / `Overrides.<name>Overrides` can
        // thread through the primary init.
        if info.scope == .shared {
            decls.append(storagePeerDecl(name: "_storage_sub_\(info.name)", type: info.type, optional: false))
        }

        decls.append(storagePeerDecl(name: "_override_sub_\(info.name)", type: info.type, optional: true))
        decls.append(subContainerApplyOverridePeerDecl(name: info.name, childType: info.type))

        // `.transient` scope needs a lazily-reinvoked builder closure. We
        // emit the storage slot here (peer role covers `_innoDISubBuild_`
        // via `prefixed`); `DIContainerMacro` populates the closure inside
        // the synthesized init, capturing a `let _lazySelf = self` snapshot
        // after all other storage is assigned so the closure can read
        // parent members through their accessors on subsequent calls.
        if info.scope == .transient {
            decls.append(subContainerBuildClosurePeerDecl(name: info.name, childType: info.type))
        }

        return decls
    }
}

extension SubContainerMacro: AccessorMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingAccessorsOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
        guard let info = extractPeerInfo(from: node, declaration: declaration) else {
            return []
        }

        let bodyExpr: ExprSyntax
        switch info.scope {
        case .shared:
            // Cached child — plain storage read.
            bodyExpr = ExprSyntax(
                DeclReferenceExprSyntax(baseName: .identifier("_storage_sub_\(info.name)"))
            )

        case .transient:
            // Fresh child each read. The stored builder closure
            // `_innoDISubBuild_<name>` is assigned by the parent init after
            // all other storage is initialized. Invoking it here re-reads
            // the captured parent snapshot, which yields a new child
            // instance per call.
            bodyExpr = ExprSyntax(FunctionCallExprSyntax(
                calledExpression: ExprSyntax(
                    DeclReferenceExprSyntax(baseName: .identifier("_innoDISubBuild_\(info.name)"))
                ),
                leftParen: .leftParenToken(),
                arguments: LabeledExprListSyntax([]),
                rightParen: .rightParenToken()
            ))
        }

        let getter = AccessorDeclSyntax(
            accessorSpecifier: .keyword(.get),
            body: CodeBlockSyntax(
                statements: CodeBlockItemListSyntax([
                    returnStmt(expr: bodyExpr)
                ])
            )
        )
        return [getter]
    }
}

// MARK: - Shared helpers

private struct SubContainerPeerInfo {
    let name: String
    let type: TypeSyntax
    let scope: SubContainerScopeValue
}

private func extractPeerInfo(
    from attribute: AttributeSyntax,
    declaration: some DeclSyntaxProtocol
) -> SubContainerPeerInfo? {
    guard let varDecl = declaration.as(VariableDeclSyntax.self) else { return nil }
    guard let binding = varDecl.bindings.first,
          let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
          let typeAnnotation = binding.typeAnnotation else {
        return nil
    }

    let args = InnoDICore.parseSubContainerArguments(attribute)
    // When `scope:` is missing we stay silent here: `DIContainerParser` sees
    // the same attribute and routes the error through the container-level
    // validator, which attaches the diagnostic to the attribute node.
    guard let scope = args.scope else { return nil }

    return SubContainerPeerInfo(
        name: identifier.identifier.text,
        type: typeAnnotation.type,
        scope: scope
    )
}

/// Walks up from the attached `@SubContainer` property to its enclosing
/// type declaration and extracts the names of every `@Provide`-annotated
/// member (in declaration order). Peer macros do not have a sibling
/// iterator exposed through `MacroExpansionContext`, but the parent
/// chain on the detached `VariableDeclSyntax` lets us traverse back to
/// the containing struct/class member block.
///
/// Returns an empty array when the traversal fails (e.g. the declaration
/// was detached by a test harness) — the fallback still compiles, just
/// without auto-matching. Callers that rely on automatic name matching
/// should therefore also be covered by `with:`-based explicit lists.
private func resolveAutoWireParentMemberNames(
    for declaration: some DeclSyntaxProtocol
) -> [String] {
    var current: Syntax? = Syntax(declaration).parent
    while let node = current {
        if let members = node.as(MemberBlockSyntax.self) {
            return members.members.compactMap { element in
                guard let varDecl = element.decl.as(VariableDeclSyntax.self),
                      InnoDICore.findAttribute(named: "Provide", in: varDecl.attributes) != nil,
                      let binding = varDecl.bindings.first,
                      let pattern = binding.pattern.as(IdentifierPatternSyntax.self) else {
                    return nil
                }
                return pattern.identifier.text
            }
        }
        current = node.parent
    }
    return []
}

/// `private var _innoDISubBuild_<name>: () -> <ChildType> = { fatalError(...) }`
///
/// Stored build closure for a `.transient` sub-container. Emitted as a peer
/// of the `@SubContainer` property with a `fatalError`-producing default so
/// Swift's definite-initialization rules are satisfied without forcing the
/// parent init to assign the closure before every `self` read. The parent
/// init re-assigns the closure after every other storage slot is filled
/// (using a `_lazySelfForSub = self` snapshot), which in practice always
/// happens before any accessor invocation — the fallback `fatalError` only
/// fires if the caller skipped the generated init entirely, which our
/// macro design does not allow.
private func subContainerBuildClosurePeerDecl(
    name: String,
    childType: TypeSyntax
) -> DeclSyntax {
    let trimmed = childType.trimmedDescription
    return """
        private var _innoDISubBuild_\(raw: name): () -> \(raw: trimmed) = {
            fatalError("_innoDISubBuild_\(raw: name) invoked before the generated init populated it. This should be unreachable — report as an InnoDI bug.")
        }
        """
}

/// `private let _override_sub_apply_<name>: ((inout <ChildType>.Overrides) -> Void)?`
///
/// Optional wedge used by the parent `Overrides.<name>Overrides` slot to
/// forward a trailing-closure override block to the child's own convenience
/// init. If the child does not declare its own `Overrides` type the Swift
/// compiler rejects this decl at the member-access site, surfacing as a
/// normal `type has no member 'Overrides'` error — intentional, documented
/// in the README caveat.
private func subContainerApplyOverridePeerDecl(
    name: String,
    childType: TypeSyntax
) -> DeclSyntax {
    let trimmed = childType.trimmedDescription
    let applyType = TypeSyntax(stringLiteral: "((inout \(trimmed).Overrides) -> Void)?")
    let decl = VariableDeclSyntax(
        modifiers: DeclModifierListSyntax([
            DeclModifierSyntax(name: .keyword(.private, trailingTrivia: .space))
        ]),
        bindingSpecifier: .keyword(.let, trailingTrivia: .space),
        bindings: PatternBindingListSyntax([
            PatternBindingSyntax(
                pattern: IdentifierPatternSyntax(identifier: .identifier("_override_sub_apply_\(name)")),
                typeAnnotation: TypeAnnotationSyntax(
                    colon: .colonToken(trailingTrivia: .space),
                    type: applyType
                )
            )
        ])
    )
    return DeclSyntax(decl)
}
