//
//  SubContainerMacro.swift
//  InnoDIMacros
//
//  First-class nested containers. `@SubContainer` expands into two roles:
//
//  1. **Peer storage** — per-member private declarations that hold the cached
//     child instance (`.shared` scope) and/or the test override wedges that
//     the parent `Overrides` builder writes into during init.
//  2. **Accessor** — a getter that either returns the cached child (for
//     `.shared`) or delegates to a parent-synthesized helper that builds a
//     fresh child on every read (for `.transient`).
//
//  The init-time wiring (assigning `_storage_sub_<name>`, applying
//  `_override_sub_<name>`, emitting the helper function for `.transient`) is
//  generated by `DIContainerMacro` / `DIContainerCodeGenerator`, which sees
//  every `@SubContainer` member via `DIContainerExpansionModel.subContainerMembers`.
//  Keeping the split here avoids duplicating "iterate every parent member"
//  logic inside an accessor macro that has no sibling visibility.
//

import InnoDICore
import SwiftSyntax
import SwiftSyntaxMacros

public struct SubContainerMacro {}

extension SubContainerMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let info = extractPeerInfo(from: node, declaration: declaration, in: context) else {
            return []
        }

        var decls: [DeclSyntax] = []

        // `.shared` caches the first-built child in a private stored property.
        // `.transient` rebuilds on every accessor read and therefore needs no
        // storage — the override wedges below are still emitted in both
        // scopes so `Overrides.<name>` / `Overrides.<name>Overrides` can
        // thread through the primary init.
        if info.scope == .shared {
            decls.append(storagePeerDecl(name: "_storage_sub_\(info.name)", type: info.type, optional: false))
        }

        decls.append(storagePeerDecl(name: "_override_sub_\(info.name)", type: info.type, optional: true))
        decls.append(
            subContainerApplyOverridePeerDecl(
                name: info.name,
                childType: info.type,
                isMainActor: info.isMainActor
            )
        )

        // `.transient` scope needs a lazily-reinvoked builder closure. We
        // emit the storage slot here (peer role covers `_innoDISubBuild_`
        // via `prefixed`); `DIContainerMacro` populates the closure inside
        // the synthesized init, capturing a `let _lazySelf = self` snapshot
        // after all other storage is assigned so the closure can read
        // parent members through their accessors on subsequent calls.
        if info.scope == .transient {
            decls.append(
                subContainerBuildClosurePeerDecl(
                    name: info.name,
                    childType: info.type,
                    isMainActor: info.isMainActor
                )
            )
        }

        return decls
    }
}

extension SubContainerMacro: AccessorMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingAccessorsOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
        guard !isEnclosedByUnsupportedDIContainer(declaration, in: context) else {
            return [unsupportedDIContainerRecoveryAccessor()]
        }

        guard let info = extractPeerInfo(from: node, declaration: declaration, in: context) else {
            return []
        }

        let bodyExpr: ExprSyntax
        switch info.scope {
        case .shared:
            // Cached child — plain storage read.
            bodyExpr = ExprSyntax(
                DeclReferenceExprSyntax(baseName: .identifier("_storage_sub_\(info.name)"))
            )

        case .transient:
            // Fresh child each read. The stored builder closure
            // `_innoDISubBuild_<name>` is assigned by the parent init after
            // all other storage is initialized. Invoking it here re-reads
            // the captured parent snapshot, which yields a new child
            // instance per call.
            bodyExpr = ExprSyntax(FunctionCallExprSyntax(
                calledExpression: ExprSyntax(
                    DeclReferenceExprSyntax(baseName: .identifier("_innoDISubBuild_\(info.name)"))
                ),
                leftParen: .leftParenToken(),
                arguments: LabeledExprListSyntax([]),
                rightParen: .rightParenToken()
            ))
        }

        let getter = AccessorDeclSyntax(
            accessorSpecifier: .keyword(.get),
            body: CodeBlockSyntax(
                statements: CodeBlockItemListSyntax([
                    returnStmt(expr: bodyExpr)
                ])
            )
        )
        return [getter]
    }
}

// MARK: - Shared helpers

private struct SubContainerPeerInfo {
    let name: String
    let type: TypeSyntax
    let scope: SubContainerScopeValue
    let isMainActor: Bool
}

private func extractPeerInfo(
    from attribute: AttributeSyntax,
    declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
) -> SubContainerPeerInfo? {
    guard !isEnclosedByUnsupportedDIContainer(declaration, in: context) else {
        return nil
    }

    guard let varDecl = declaration.as(VariableDeclSyntax.self) else { return nil }
    guard let binding = varDecl.bindings.first,
          let identifier = binding.pattern.as(IdentifierPatternSyntax.self),
          let typeAnnotation = binding.typeAnnotation else {
        return nil
    }

    let args = InnoDICore.parseSubContainerArguments(attribute)
    // When `scope:` is missing we stay silent here: `DIContainerParser` sees
    // the same attribute and routes the error through the container-level
    // validator, which attaches the diagnostic to the attribute node.
    guard let scope = args.scope else { return nil }

    // Prefer lexical expansion context when SwiftSyntaxMacros provides it,
    // then fall back to walking out from the attribute and declaration nodes.
    // If no enclosing @DIContainer is visible through any path we conservatively
    // treat the property as non-MainActor.
    return SubContainerPeerInfo(
        name: identifier.identifier.text,
        type: typeAnnotation.type,
        scope: scope,
        isMainActor: (
            enclosingDIContainerInfo(in: context) ??
            enclosingDIContainerInfo(startingAt: Syntax(attribute)) ??
            enclosingDIContainerInfo(startingAt: Syntax(declaration))
        )?.mainActor == true
    )
}

/// `private let _override_sub_apply_<name>: ([@MainActor] (inout <ChildType>.Overrides) -> Void)?`
///
/// Optional wedge used by the parent `Overrides.<name>Overrides` slot to
/// forward a trailing-closure override block to the child's own convenience
/// init. Input-only child containers synthesize an empty `Overrides` type, so
/// this closure still type-checks and simply applies no overrideable members
/// until the child grows `.shared`, `.transient`, or nested child slots.
private func subContainerApplyOverridePeerDecl(
    name: String,
    childType: TypeSyntax,
    isMainActor: Bool
) -> DeclSyntax {
    let trimmed = childType.trimmedDescription
    let applyType = overrideApplyClosureType(
        overridesTypeDescription: "\(trimmed).Overrides",
        isMainActor: isMainActor,
        isOptional: true
    )
    let decl = VariableDeclSyntax(
        modifiers: DeclModifierListSyntax([
            DeclModifierSyntax(name: .keyword(.private, trailingTrivia: .space))
        ]),
        bindingSpecifier: .keyword(.let, trailingTrivia: .space),
        bindings: PatternBindingListSyntax([
            PatternBindingSyntax(
                pattern: IdentifierPatternSyntax(identifier: .identifier("_override_sub_apply_\(name)")),
                typeAnnotation: TypeAnnotationSyntax(
                    colon: .colonToken(trailingTrivia: .space),
                    type: applyType
                )
            )
        ])
    )
    return DeclSyntax(decl)
}

private func enclosingDIContainerInfo(startingAt syntax: Syntax) -> DIContainerAttributeInfo? {
    var current: Syntax? = syntax.parent

    while let node = current {
        if let declGroup = declGroupSyntax(from: node),
           let info = diContainerAttributeInfo(in: declGroup) {
            return info
        }
        current = node.parent
    }

    return nil
}

private func enclosingDIContainerInfo(in context: some MacroExpansionContext) -> DIContainerAttributeInfo? {
    for node in context.lexicalContext.reversed() {
        if let declGroup = declGroupSyntax(from: node),
           let info = diContainerAttributeInfo(in: declGroup) {
            return info
        }
    }

    return nil
}

private func diContainerAttributeInfo(in declaration: some DeclGroupSyntax) -> DIContainerAttributeInfo? {
    parseDIContainerAttribute(declaration.attributes)
}

private func declGroupSyntax(from syntax: Syntax) -> (any DeclGroupSyntax)? {
    if let structDecl = syntax.as(StructDeclSyntax.self) {
        return structDecl
    }
    if let classDecl = syntax.as(ClassDeclSyntax.self) {
        return classDecl
    }
    if let actorDecl = syntax.as(ActorDeclSyntax.self) {
        return actorDecl
    }
    if let enumDecl = syntax.as(EnumDeclSyntax.self) {
        return enumDecl
    }
    return nil
}
