#!/usr/bin/env bash
# Build a SwiftPM package with the compiler's macro-expansion dump enabled and
# extract only the generated Swift fragments into one reviewable artifact.

set -euo pipefail

PACKAGE_PATH="."
OUTPUT_PATH=""
TARGET=""
CONFIG="debug"
SWIFT_EXECUTABLE="${INNODI_SWIFT_EXECUTABLE:-swift}"

usage() {
    cat <<'USAGE'
Usage: Tools/dump-macro-expansions.sh [options]

Options:
  --package-path <path>       Consumer SwiftPM package (default: current directory)
  --output <path>             Combined generated Swift output
                              (default: <package>/.build/innodi/macro-expansions.swift)
  --target <name>             Build only one consumer target
  --config <debug|release>    Build configuration (default: debug)
  --help                      Show this help
USAGE
}

require_value() {
    local option="$1"
    local value="${2:-}"
    if [[ -z "$value" || "$value" == -* ]]; then
        echo "Error: $option requires a value." >&2
        usage >&2
        exit 2
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --package-path)
            require_value "$1" "${2:-}"
            PACKAGE_PATH="$2"
            shift 2
            ;;
        --output)
            require_value "$1" "${2:-}"
            OUTPUT_PATH="$2"
            shift 2
            ;;
        --target)
            require_value "$1" "${2:-}"
            TARGET="$2"
            shift 2
            ;;
        --config)
            require_value "$1" "${2:-}"
            CONFIG="$2"
            shift 2
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

case "$CONFIG" in
    debug|release) ;;
    *)
        echo "Error: --config must be 'debug' or 'release'." >&2
        exit 2
        ;;
esac

if [[ ! -d "$PACKAGE_PATH" ]]; then
    echo "Error: package directory does not exist: $PACKAGE_PATH" >&2
    exit 2
fi
PACKAGE_PATH="$(cd "$PACKAGE_PATH" && pwd -P)"
if [[ ! -f "$PACKAGE_PATH/Package.swift" ]]; then
    echo "Error: no Package.swift at $PACKAGE_PATH" >&2
    exit 2
fi

if [[ -z "$OUTPUT_PATH" ]]; then
    OUTPUT_PATH="$PACKAGE_PATH/.build/innodi/macro-expansions.swift"
elif [[ "$OUTPUT_PATH" != /* ]]; then
    OUTPUT_PATH="$(pwd -P)/$OUTPUT_PATH"
fi

OUTPUT_PARENT="$(dirname "$OUTPUT_PATH")"
mkdir -p "$OUTPUT_PARENT"
OUTPUT_PARENT="$(cd "$OUTPUT_PARENT" && pwd -P)"
OUTPUT_PATH="$OUTPUT_PARENT/$(basename "$OUTPUT_PATH")"

case "$OUTPUT_PATH" in
    "$PACKAGE_PATH/Sources"|"$PACKAGE_PATH/Sources/"*|\
    "$PACKAGE_PATH/Tests"|"$PACKAGE_PATH/Tests/"*)
        echo "Error: expansion output must stay outside consumer Sources/ and Tests/." >&2
        exit 2
        ;;
esac

TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/innodi-macro-expansions.XXXXXX")"
trap 'rm -rf "$TEMP_DIR"' EXIT
BUILD_LOG="$TEMP_DIR/build.log"
EXTRACTED_OUTPUT="$TEMP_DIR/macro-expansions.swift"
SCRATCH_PATH="$TEMP_DIR/scratch"

BUILD_COMMAND=(
    "$SWIFT_EXECUTABLE" build
    --package-path "$PACKAGE_PATH"
    --scratch-path "$SCRATCH_PATH"
    -c "$CONFIG"
)
if [[ -n "$TARGET" ]]; then
    BUILD_COMMAND+=(--target "$TARGET")
fi
BUILD_COMMAND+=(
    -Xswiftc -Xfrontend
    -Xswiftc -dump-macro-expansions
)

if ! "${BUILD_COMMAND[@]}" >"$BUILD_LOG" 2>&1; then
    echo "Error: consumer build failed while dumping macro expansions." >&2
    cat "$BUILD_LOG" >&2
    exit 1
fi

SWIFT_VERSION_OUTPUT="$($SWIFT_EXECUTABLE --version 2>/dev/null)"
SWIFT_VERSION="${SWIFT_VERSION_OUTPUT%%$'\n'*}"
if ! awk -v swift_version="$SWIFT_VERSION" '
    BEGIN {
        state = 0
        count = 0
        print "// InnoDI macro expansions"
        print "// Generated by Tools/dump-macro-expansions.sh"
        print "// " swift_version
        print "// Inspection artifact only; do not add this file to a build target."
        print ""
    }
    state == 0 && /^@__swiftmacro_.*\.swift$/ {
        expansion_name = $0
        state = 1
        next
    }
    state == 1 {
        if ($0 ~ /^-+$/) {
            count += 1
            print "// MARK: - " expansion_name
            state = 2
        } else {
            state = 0
        }
        next
    }
    state == 2 && /^-+$/ {
        print ""
        state = 0
        next
    }
    state == 2 { print }
    END { if (count == 0) exit 42 }
' "$BUILD_LOG" >"$EXTRACTED_OUTPUT"; then
    echo "Error: build succeeded but the compiler emitted no macro expansions." >&2
    echo "Confirm that the selected target uses macros and the Swift toolchain supports -dump-macro-expansions." >&2
    exit 1
fi

mv "$EXTRACTED_OUTPUT" "$OUTPUT_PATH"
EXPANSION_COUNT="$(grep -c '^// MARK: - @__swiftmacro_' "$OUTPUT_PATH")"
echo "Wrote $EXPANSION_COUNT macro expansion(s) to $OUTPUT_PATH"
